spellername = "Eastern Mari"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Eastern Mari spellchecker"
mhr = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Eastern Mari, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
mhr = "TRANSLATE: A spellchecker for Eastern Mari, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.mhr"

[windows]
system_product_code = "{DC64647C-2BE2-40D2-93D9-C0C454253BC7}_is1"
legacy_product_codes = [
    { value = "B38FF964-580D-4DB3-A318-7A107C8B8BD5", kind = "nsis" },
    { value = "F1849E44-9904-472A-9938-D7C6E306F848", kind = "nsis" }
]
extra_locales = { mhr-RU = "mhr" }
