template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "east2328"
__REPO__ = "lang-mhr"
__UND2C__ = "mhr"
__UNDEFINED__ = "Eastern Mari"
__UND__ = "mhr"
