template = "https://github.com/giellalt/template-lang-und"
rev_id = 333
template_sha = "a03015fd00a15a0ad51da907dc4891c29ab9c8b2"

[replacements]
__GLOTTOLOG_ID__ = "east2328"
__REPO__ = "lang-mhr"
__UND2C__ = "mhr"
__UNDEFINED__ = "Eastern Mari"
__UND__ = "mhr"
