template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "east2328"
__REPO__ = "lang-mhr"
__UND2C__ = "mhr"
__UNDEFINED__ = "Eastern Mari"
__UND__ = "mhr"
