[package]
name = "mhr"
human_name = "Eastern Mari"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.mhr]
filename = "mhr-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-mhr"
platform = "windows"
uuid = "B38FF964-580D-4DB3-A318-7A107C8B8BD5"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.mhr"
package = "speller-mhr"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-mhr-mso"
platform = "windows"
uuid = "F1849E44-9904-472A-9938-D7C6E306F848"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-mhr"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
